[command]
default=extract_source.sh

[file:get_git_sources.py]
source=/data/users/robert.waters/local_repos/SimSys_Scripts/SimSys_Scripts/github_scripts/get_git_sources.py

[file:rose_stem_extract_source.py]
source=/data/users/robert.waters/local_repos/SimSys_Scripts/SimSys_Scripts/github_scripts/rose_stem_extract_source.py
